import { useState } from 'react';
import { DollarSign, Plus, Edit2, Save, X, FileText } from 'lucide-react';
import { useDataStore } from '../../store/dataStore';

interface FeeStructure {
  id: string;
  classId: string;
  termId: string;
  tuitionFee: number;
  examFee: number;
  activityFee: number;
  labFee: number;
  otherFee: number;
}

const defaultStructures: FeeStructure[] = [
  { id: 'fs1', classId: 'c1', termId: 't1', tuitionFee: 800, examFee: 100, activityFee: 50, labFee: 80, otherFee: 20 },
  { id: 'fs2', classId: 'c2', termId: 't1', tuitionFee: 650, examFee: 80, activityFee: 50, labFee: 60, otherFee: 20 },
  { id: 'fs3', classId: 'c3', termId: 't1', tuitionFee: 1000, examFee: 120, activityFee: 60, labFee: 100, otherFee: 30 },
];

const FEE_FIELDS: { key: keyof Omit<FeeStructure,'id'|'classId'|'termId'>; label: string }[] = [
  { key: 'tuitionFee',  label: 'Tuition Fee' },
  { key: 'examFee',     label: 'Exam Fee' },
  { key: 'activityFee', label: 'Activity Fee' },
  { key: 'labFee',      label: 'Lab / Resource Fee' },
  { key: 'otherFee',    label: 'Other Fees' },
];

export default function FeeStructures() {
  const TERMS = useDataStore(s => s.terms);
  const CLASSES = useDataStore(s => s.classes);
  const currentTerm = TERMS.find(t => t.isCurrent) || TERMS[0];
  
  if (!currentTerm) {
    return <div style={{ padding: 40, textAlign: 'center', color: '#64748b' }}>No active academic term found. Please configure terms in Academic Setup.</div>;
  }

  const [structures, setStructures] = useState<FeeStructure[]>([]);
  const [editId, setEditId] = useState<string | null>(null);
  const [editData, setEditData] = useState<Partial<FeeStructure>>({});
  const [showNew, setShowNew] = useState(false);
  const [newForm, setNewForm] = useState<Omit<FeeStructure,'id'>>({
    classId: CLASSES[0]?.id ?? '', termId: currentTerm.id,
    tuitionFee: 0, examFee: 0, activityFee: 0, labFee: 0, otherFee: 0,
  });

  const total = (s: FeeStructure) => s.tuitionFee + s.examFee + s.activityFee + s.labFee + s.otherFee;

  const handleEdit = (s: FeeStructure) => { setEditId(s.id); setEditData({ ...s }); };
  const handleSave = () => {
    setStructures(prev => prev.map(s => s.id === editId ? { ...s, ...editData } : s));
    setEditId(null);
  };
  const handleAdd = () => {
    setStructures(prev => [...prev, { id: `fs${Date.now()}`, ...newForm }]);
    setShowNew(false);
    setNewForm({ classId: CLASSES[0]?.id ?? '', termId: currentTerm.id, tuitionFee: 0, examFee: 0, activityFee: 0, labFee: 0, otherFee: 0 });
  };

  const exportInvoiceTemplate = (s: FeeStructure) => {
    const cls = CLASSES.find(c => c.id === s.classId);
    const rows = FEE_FIELDS.map(f => `<tr><td>${f.label}</td><td style="text-align:right">UGX ${s[f.key].toLocaleString()}</td></tr>`).join('');
    const html = `
      <html><head><style>
        body{font-family:Arial;padding:40px;max-width:600px;margin:0 auto}
        h1{font-size:22px;text-align:center}
        .sub{text-align:center;color:#555;font-size:13px;margin-bottom:24px}
        table{width:100%;border-collapse:collapse}
        th,td{padding:10px 14px;border:1px solid #ddd;font-size:13px}
        th{background:#f0f0f0;font-weight:700}
        .total{font-weight:900;font-size:16px;color:#a855f7}
      </style></head><body>
        <h1>Base2 Science and Media Academy</h1>
        <div class="sub">Fee Structure — ${cls?.name} · ${currentTerm.name}</div>
        <table>
          <thead><tr><th>Fee Component</th><th>Amount (UGX)</th></tr></thead>
          <tbody>${rows}
            <tr><td class="total">TOTAL</td><td style="text-align:right" class="total">UGX ${total(s).toLocaleString()}</td></tr>
          </tbody>
        </table>
        <p style="font-size:11px;color:#999;margin-top:32px;text-align:center">Generated by Base2 Science and Media Academy SMS</p>
      </body></html>
    `;
    const w = window.open('', '_blank');
    if (!w) return;
    w.document.write(html);
    w.document.close();
    setTimeout(() => w.print(), 300);
  };

  return (
    <div>
      <div className="page-header">
        <div><h2>Fee Structures</h2><p>Manage term fees per class · {currentTerm.name}</p></div>
        <button id="btn-add-fee-structure" className="btn btn-primary" onClick={() => setShowNew(true)}>
          <Plus size={14}/> Add Structure
        </button>
      </div>

      {/* Summary cards */}
      <div className="stat-grid" style={{ marginBottom: 24 }}>
        {structures.map(s => {
          const cls = CLASSES.find(c => c.id === s.classId);
          return (
            <div className="stat-card" key={s.id} style={{ borderTopColor: '#a855f7' }}>
              <div className="stat-icon" style={{ background: '#a855f718', color: '#a855f7' }}><DollarSign size={20}/></div>
              <div className="stat-body">
                <div className="stat-value" style={{ color: '#a855f7', fontSize: 22 }}>UGX {total(s).toLocaleString()}</div>
                <div className="stat-label">{cls?.name ?? '—'}</div>
                <div className="stat-delta" style={{ color: '#64748b' }}>per term total</div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Fee structures table */}
      <div className="card" style={{ padding: 0 }}>
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th>Class</th>
                {FEE_FIELDS.map(f => <th key={f.key}>{f.label}</th>)}
                <th>Total</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {structures.map(s => {
                const cls = CLASSES.find(c => c.id === s.classId);
                const isEditing = editId === s.id;
                return (
                  <tr key={s.id}>
                    <td style={{ fontWeight: 700 }}>{cls?.name ?? '—'}</td>
                    {FEE_FIELDS.map(f => (
                      <td key={f.key}>
                        {isEditing ? (
                          <input
                            type="number"
                            className="score-input"
                            style={{ width: 90 }}
                            value={(editData as any)[f.key] ?? s[f.key]}
                            onChange={e => setEditData(prev => ({ ...prev, [f.key]: Number(e.target.value) }))}
                          />
                        ) : (
                          <span style={{ fontWeight: 600 }}>UGX {s[f.key].toLocaleString()}</span>
                        )}
                      </td>
                    ))}
                    <td style={{ fontWeight: 900, color: '#a855f7' }}>UGX {total(isEditing ? { ...s, ...editData } as FeeStructure : s).toLocaleString()}</td>
                    <td>
                      <div style={{ display: 'flex', gap: 6 }}>
                        {isEditing ? (
                          <>
                            <button id={`save-fee-${s.id}`} className="btn btn-staff btn-sm" onClick={handleSave}><Save size={12}/></button>
                            <button className="btn btn-ghost btn-sm" onClick={() => setEditId(null)}><X size={12}/></button>
                          </>
                        ) : (
                          <>
                            <button id={`edit-fee-${s.id}`} className="btn btn-ghost btn-sm" onClick={() => handleEdit(s)}><Edit2 size={12}/></button>
                            <button id={`invoice-fee-${s.id}`} className="btn btn-ghost btn-sm" title="Print Invoice Template" onClick={() => exportInvoiceTemplate(s)}><FileText size={12}/></button>
                          </>
                        )}
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* Add new structure modal */}
      {showNew && (
        <div className="modal-overlay" onClick={() => setShowNew(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header"><h3>New Fee Structure</h3><button className="modal-close" onClick={() => setShowNew(false)}>✕</button></div>
            <div className="modal-body">
              <div className="form-group">
                <label className="form-label">Class</label>
                <select className="form-select" value={newForm.classId} onChange={e => setNewForm(p => ({...p, classId: e.target.value}))}>
                  {CLASSES.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
                </select>
              </div>
              <div className="form-row">
                {FEE_FIELDS.map(f => (
                  <div className="form-group" key={f.key}>
                    <label className="form-label">{f.label} (UGX)</label>
                    <input type="number" className="form-input" value={(newForm as any)[f.key]} onChange={e => setNewForm(p => ({...p, [f.key]: Number(e.target.value)}))}/>
                  </div>
                ))}
              </div>
              <div style={{ padding: '10px 14px', background: 'rgba(168,85,247,0.08)', borderRadius: 8, fontSize: 13, fontWeight: 700, color: '#a855f7' }}>
                Total: UGX {(newForm.tuitionFee + newForm.examFee + newForm.activityFee + newForm.labFee + newForm.otherFee).toLocaleString()}
              </div>
            </div>
            <div className="modal-footer">
              <button className="btn btn-ghost" onClick={() => setShowNew(false)}>Cancel</button>
              <button id="btn-save-fee-structure" className="btn btn-primary" onClick={handleAdd}><Save size={14}/> Save Structure</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
